### ISSUE TITLE
Audio conversion service

### ISSUE THREAD

**Issue by jhauswald** [clinc/clarityeco#13]
- Description: this service receives audio and converts it to the user's specified audio format.
- Input: audio, desired format
- Output: audio in requested format
- Potential dependencies: ffmpeg, sox, thrift

**Comment by cdmeister** [comment]
Currently working on it.

**Comment by cdmeister** [comment]
Current Status:
I am able to take the android audio file and separate the audio from the file and decode it into raw universal format. Also I am able to  create a new file that has the riff header so the when you write click on the file it properly identifies it as a WAV file. I am currently working on taking the raw encoded data and encode that into a wav format with 8000Hz as requested for Kaldi.

**Comment by cdmeister** [comment]
Current Status:
Able to successfully convert android's audio file to wav using ffmpeg api. Now testing to see if Kaldi will recognize it.

**Comment by cdmeister** [comment]
Kaldi recognizes the new wav file. One interesting aspect I found is that when i use the audio conversion I made up and ffmpeg's binary for conversion, they get similar answers from Kaldi but not the same.

**Comment by cdmeister** [comment]
As discussed with Tim and Johann here are our options so far:

1. cc->asr-->audio_conv-->asr-->rest of pipeline
2. cc--> audio_conv-->cc-->asr-->rest of pipline 

In option 2, the audio_conv service registers with the command centre and the work flow changes. 

Current Status:
I created a template version of the audio_conv service. I am making a 'sirius' version that will register with the command center(option 2). I pretty sure there are memory leaks so I will check for that last. Once I have the sirius version working, I will remove sox from asr  and start to test more. Android platform wont send a request to the node js server when we try to do a asr request. currently text and image only work with the node js server.

**Comment by cdmeister** [comment]
I disabled sox(), but now Kaldi claims about a premature EOF on the converted wav file for some of the audio files. I am taking a look into it. It maybe that I might have to restructure the code.

**Comment by jhauswald** [comment]
I had something written up and misunderstood the message. Senna and djinn have a similar workflow so either is fine, it should just be consistent: i.e if a service needs another service they should all either go back to the cc or talk directly to it.

This could create a long chain though if that service also needs another one etc. Going back to the CC everytime could make sure there aren't long chains of services talking to each other.

**Comment by cdmeister** [comment]
At this point its not to hard to swap it around to a different option. 

Current Status:

I figured out that after disabling sox and using the custom ffmpeg, it creates a header that is not standard for Kaldi. Sox creates a "canonical wave header" and that is what kaldi is expecting. I am researching some ways if I can fix the header size.

**Comment by cdmeister** [comment]
Current Status:

The riff header of wav file is now the standard 44-byte canonical wav header. There was a couple of lines of code I had to insert to make it work after reading some more of the documentation. The conversion function is all in one function so it doesn't matter what kind of audio file it is, it will convert it to Kaldi specifications. I am working on clean up the code. I ran a couple of files through Kaldi and things seem to be stable. I edited the command centre and the audio conversion service will register and also I edited the work flow as well.

**Comment by jhauswald** [comment]
Does it matter what audio the ASR expects? i.e what if pocketsphinx needs a different type of audio? How do you handle that?

**Comment by cdmeister** [comment]
Well its hard coded for Kaldi right now. If it needs to be more modular, I could, pass in parameters to the audio service so depending on the asr, you give it the parameters that it requires.  Any other ideas?

**Comment by cdmeister** [comment]
Just a side note, we should come up with some audio test suite for asr. for example, what.is.the.author.of.harry.potter.wav will not translate well from speech to text. I tried it with both ffmpeg and sox

**Comment by jhauswald** [comment]
I agree this could fit in well with the testing framework we are thinking of including.

**Comment by cdmeister** [comment]
Hey @Thomas-Yang, here is the issue of the audio conversion service. if you got any issues let me know.

**Comment by cdmeister** [comment]
Hey Johann,

I came up with an idea to make it more modular. I created a struct called audioSpecs which defines how you want your output to look like:
```c++
struct audioSpecs{
  int sample_rate;
  int bit_rate;
  int channels;
 string output_format;
}
```
The string `output_format` defines what kind of file you want. So for instance, if you want and MP3 audio file:
`output_format="mp3"` 

or if you want a Wav:
`output_format="wav"`

then you pass the struct into the conversion function and it takes care of the rest. 
if `sample_rate` or `bit_rate` or channels` equals to `0`, then it uses the default values.

what do you think?

**Comment by Thomas-Yang** [comment]
There is a new query data structure defined in the new command center, which is supposed to be flexible to support all kinds of input and its corresponding parameters. Therefore, you don't have to define a new query data structure per service. For example, the sample_rate, bit_rate and channels can all be put into the tags indicating which kind of output you want from the conversion service.

**Comment by cdmeister** [comment]
Would all services then need to support this new query data structure then?

**Comment by twurman** [comment]
Yep

On Thursday, July 16, 2015, cdmeister <notifications@github.com> wrote:

> Would all services then need to support this new query data structure
> then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clarityinc/clarityeco/issues/13#issuecomment-121962607>
> .
>


-- 
Timothy R. Wurman
University of Michigan
BSE Computer Science
twurman@umich.edu | 978-760-2208

**Comment by cdmeister** [comment]
Where do I find the new command center stuff? I am getting lost.

**Comment by cdmeister** [comment]
Nvm Jessica showed me..................

**Comment by cdmeister** [comment]
I got the audio service to be a multithreaded(TThreadPoolServer) server as an IPAservice. It at the moment it registers with the command center. Originally when I started converting it into an IPAservice, I took out the audio portion and just wanted to get the other parts working. Now I am going to insert the audio code stuff back in.

**Comment by jhauswald** [comment]
Maybe this is nitpicking but why is it called an IPAservice? isnt it just a service?

**Comment by Thomas-Yang** [comment]
It was the name that came into my mind when I was defining the interface. I agree it sounds a little bit bias since not all services are limited to IPA. We can change it to a more general name that applies to all cases.

**Comment by cdmeister** [comment]
made a client and inserted the audio conversion code back in and it is working. I just need to add the boost programs options as cmd args parsing #27 and will be submitting a pull request.

**Comment by cdmeister** [comment]
Created a new branch called audio_conv_ipa and will use that to submit pull request
