### ISSUE TITLE
IMM Service enhancements

### ISSUE THREAD

**Issue by jhauswald** [clinc/clarityeco#19]
IMM service fixups after #6: 
- Option to build and save model, currently builds new model every time
- option to build different database, currently hard coded.
- log folder
- GPU option
- debug option isn't used anywhere
- remove timing
- currently odd input handling. if passed in different order, "breaks". probably use better input parsing (boost options?) As discussed this will be formalized by @Lilisys 
- OCR code is in there but isn't used either move it out to #18 or merge the services together

**Comment by cdmeister** [comment]
I am working on this now.

**Comment by jhauswald** [comment]
there's the possibility to run the IMM service using the GPU. The code is in there but currently no options to explicitly say "use GPU" See https://github.com/clarityinc/clarityeco/blob/dev/imm/common/detect.cpp#L45-L67

**Comment by cdmeister** [comment]
I see. It looks like you also have to build the database with  "SURF" if you are gonna run with the gpu option. 

For input handling, I am gonna use boost::program_options #27

**Comment by jhauswald** [comment]
Yea but the CPU option is also using SURF so I think OpenCV doesnt care who/where its built. You could probably also use the GPU to build the database which would speed up that process as well.

**Comment by cdmeister** [comment]
Also, is there any purpose to the keypoint.proto files?

**Comment by jhauswald** [comment]
Its to store the descriptors of each image as protobuf files. In the current implementation, I think the database is generated new everytime which (for now) is ok since the DB is small. For a larger database this will be a problem since generating descriptors is expensive. It'd be better to save all the descriptors and just load them in when building the model (or even better just save the model).

**Comment by jhauswald** [comment]
The descriptors represent the contents of the image and are used to match the input image to that database.

**Comment by cdmeister** [comment]
i see. I was getting confused since some of the files are named similar.  In https://github.com/claritylab/sirius/blob/master/sirius-application/image-matching/keypoints.proto#L27-35. Is the Keypoint something you made up or an opencv then that your trying to use protobuf with. I want to get rid of all of the protobuf files but I am getting a little bit confused whats what.

**Comment by cdmeister** [comment]
Ok I see now what is going on. I was getting confused. I initially thought that protobuf was like thrift but it is a little bit different. I see what is going on with the code. We will keep the protobuf stuff then.

**Comment by cdmeister** [comment]
do you have to train the model every time before you start matching? Also "Option to build and save model, currently builds new model every time", are you referring to creating the .pb files?

**Comment by cdmeister** [comment]
There is some redundant logic between exec_match and build_model. 
https://github.com/claritylab/sirius/blob/master/sirius-application/image-matching/detect.cpp#L317-L339
https://github.com/claritylab/sirius/blob/master/sirius-application/image-matching/detect.cpp#L204-L235
