### ISSUE TITLE
Glog: Output Logging

### ISSUE THREAD

**Issue by jhauswald** [clinc/clarityeco#29]
We should move all the output logging to use a standard system. [Glog](https://google-glog.googlecode.com/svn/trunk/doc/glog.html) provides a nice way to output messages at different error levels.  

In some cases something like `LOG(FATAL) << "this should not execute"` will terminate while `LOG(ERROR) << "bad execution"` with continue executing.

What do you guys think? I think this can be included in the next release with #15 #25 #26 #19

**Comment by Thomas-Yang** [comment]
Can I also suggest the logging facilities for Java <http://logging.apache.org/log4j/2.x/> and Python <https://docs.python.org/2/library/logging.html>?
