### ISSUE TITLE
[Release] Changelogrc

### ISSUE THREAD

**Issue by jhauswald** [clinc/clarityeco#46]
Came across a `.gitchangelog.rc` I don't really know what this is but seems useful for what @Thomas-Yang and I were talking about today for releasing and writing changelogs. Let's investigate this:

https://github.com/NervanaSystems/neon/blob/master/.gitchangelog.rc

**Comment by Thomas-Yang** [comment]
Is this a special format for tracking the changes in github? I was thinking something like this [https://github.com/apache/mesos/blob/master/CHANGELOG](https://github.com/apache/mesos/blob/master/CHANGELOG)

**Comment by jhauswald** [comment]
So I think that file you mention is autogenerated based on annotated commits using the .gitchangelogrc. They would work together but yea something like that is also what I'm thinking. No chance someone wrote that thing, its huge! That's the nice thing about rebased commits and stuff, you can use them as actual messages.

**Comment by Thomas-Yang** [comment]
I agree. We should definitely adopt the procedure to auto generate the change logs.
